### ISSUE TITLE
Getting started example does not work

### ISSUE THREAD

**Issue by clkotnik** [indilib/pyindi-client#2] opened 2021-08-22 18:54 UTC
When I run the getting started example program it failed on line 83 with:

> TypeError: 'SwigPyObject' object is not iterable

Complete output here:
[output.txt](https://github.com/indilib/pyindi-client/files/7027953/output.txt)

My environment is:
ubuntu 20.04
Python 3.8.10
indi-full 1.9.1 package from ppa:mutlaqja/ppa
pyindi-client                 0.2.7 installed with pip

best regards,
Cliff

**Comment by aaronwmorris** [comment] 2021-08-23 23:12
PyPI does not have the latest code for pyindi-client.  You will need to install directly from git

`pip install git+https://github.com/indilib/pyindi-client.git@68803a1#egg=pyindi-client`

**Comment by fockez** [comment] 2021-09-18 15:51
install new code is no help

**Comment by gnthibault** [comment] 2021-09-30 19:38
Same issue here, there are apparently quite some changes with the latest versions of indi/pyindi bindings. But as there are no tests it seems difficult to keep track of potential regressions and what is causing them.

Just and example, given an object of type:
`<PyIndi.ISwitchPropertyview; proxy of <Swig Object of type 'INDI::PropertyView< ISwitch > *' at 0x7fb3cc8c3300> >`
called pv, it was possible before to iterate over it, and it was offering method like:
`pv.r`
to get the rule, and now it is called:
`pv.getRule()`

I can get the methods that makes it looks like and iterator like begin() next() and end() and count() but it is impossible to iterate over this object in python.
It does not offers the [] operator access anymore, as it used to do in the past, neither the len().

As I was playing with connect switch, I was eventually able to get an object of type `<Swig Object of type 'INDI::PropertyView< _ISwitch >::WidgetType *' at 0x7f5b27c8d3f0>`
 by doing the following query:
`pv.findWidgetByName("CONNECT")`
and
`pv.findWidgetByName("DISCONNECT")`

but this is not what one wants to do in general, as you'd prefer to iterate over the list of switch elements to check for what's available and what is not.

Also, before, it was possible to get acces to attribute "name" on each property, now here is what I get from the returned value from findWIdgetByName:

```
test = pv.findWidgetByName("CONNECT")
test.name
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-51046e3b0758>", line 1, in <module>
    test.name
AttributeError: 'SwigPyObject' object has no attribute 'name'
```

EDIT: ok I moved away from the python bindings, now using pure python client lower the risks of incompatibility such as this one. You might be interested by this this code: https://github.com/MMTObservatory/indiclient/blob/master/indiclient/indiclient.py

**Comment by aaronwmorris** [comment] 2021-10-01 00:50
> Also, before, it was possible to get acces to attribute "name" on each property, now here is what I get from the returned value from findWIdgetByName:
> 
> ```
> test = pv.findWidgetByName("CONNECT")
> test.name
> Traceback (most recent call last):
>   File "/home/user/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-5-51046e3b0758>", line 1, in <module>
>     test.name
> AttributeError: 'SwigPyObject' object has no attribute 'name'
> ```

I think direct access to some of the attributes are no longer available.  I had to convert to using functions to fetch the attributes, such as getName() instead of accessing .name

**Comment by gnthibault** [comment] 2021-10-01 11:33
Based on https://github.com/indilib/indi/blob/723ae45593d204388cec337396be4c3b8300255c/libs/indibase/property/indipropertyview.h#L159 I was curious wether @pawel-soja had an idea about what is going on ? might create an issue in main indi repo

**Comment by artak-kirakosyan** [comment] 2021-11-06 15:09
> PyPI does not have the latest code for pyindi-client. You will need to install directly from git
> 
> `pip install git+https://github.com/indilib/pyindi-client.git@68803a1#egg=pyindi-client`

Installing from this link solved the issue for me, however a lot of object types have changed, for example, 'ITextVectorProperty' became 'PropertyViewText' .

**Comment by artak-kirakosyan** [comment] 2021-11-06 15:15
An alternative to git install is using
 ```pip install pyindi-client==0.2.7b0```
 
I believe we just need a new release for PyPi so that people can get the fresh fixes from PyPi directly.
@knro what do you think?

**Comment by knro** [comment] 2021-11-06 15:22
I agree, we really need someone more versed in Python to take of of pyindi-client, I'm already busy with the C++ INDI. Any volunteers who can manage this?

**Comment by artak-kirakosyan** [comment] 2021-11-06 15:27
I wouldn't say I am an advanced Python engineer, but I am using this in my everyday routine so I would really like to make it a good library.

I will start researching about how the PyPi releases work and update here.

Are there any better channels for communication or this Issue is good enough?

**Comment by knro** [comment] 2021-11-06 16:33
This issue is good. I asked Jean-Luc to transfer PyPi over for a new maintainer.

**Comment by knro** [comment] 2021-11-06 17:04
@artak-kirakosyan If you have a PyPi username, please let me know so I add you as maintainer.

**Comment by artak-kirakosyan** [comment] 2021-11-06 17:06
@knro  here it is: artak-kirakosyan

**Comment by knro** [comment] 2021-11-06 18:10
I sent you an invitation, please check.

**Comment by artak-kirakosyan** [comment] 2021-11-06 18:40
I haven't received anything, could you please double check if you sent it to this profile? https://pypi.org/user/artak-kirakosyan
You can also try to find me via my email: artakkirakosyan96@gmail.com

**Comment by artak-kirakosyan** [comment] 2021-11-22 10:20
@clkotnik @aaronwmorris @fockez @gnthibault I uploaded the latest version to PyPi.
Please install the 0.2.8 version and let me know if the issue is not fixed

**Comment by aaronwmorris** [comment] 2021-11-22 15:23
Worked for me.

**Comment by artak-kirakosyan** [comment] 2021-12-20 17:40
@knro please close this issue or give me access to do it.
Looks like updating the version fixed the problem.

**Comment by knro** [comment] 2021-12-21 05:01
@artak-kirakosyan You're the repo maintainer now!

**Closed as completed** 2021-12-21 05:40 UTC
Labels: help wanted

**Comment by abecadel** [comment] 2022-01-10 00:59
@knro  I would like to help maintaining this repo as well
already helped with original repo https://github.com/geehalel/pyindi-client/commit/6c72b1ab29dcd33e6fb454fc74df6d9e45a1e119

**Comment by knro** [comment] 2022-01-10 04:39
Sure @abecadel , you have access now. Please coordinate with @artak-kirakosyan
